# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Programming\CodeProjects\QffmpegUI\QffmpegUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_winMain(object):
    def setupUi(self, winMain):
        winMain.setObjectName("winMain")
        winMain.resize(413, 190)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(winMain.sizePolicy().hasHeightForWidth())
        winMain.setSizePolicy(sizePolicy)
        winMain.setMinimumSize(QtCore.QSize(413, 190))
        winMain.setMaximumSize(QtCore.QSize(413, 190))
        self.centralwidget = QtWidgets.QWidget(winMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 391, 171))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tabFile = QtWidgets.QWidget()
        self.tabFile.setObjectName("tabFile")
        self.btnFileBrowser = QtWidgets.QPushButton(self.tabFile)
        self.btnFileBrowser.setGeometry(QtCore.QRect(315, 7, 61, 20))
        self.btnFileBrowser.setObjectName("btnFileBrowser")
        self.lblTotalFiles = QtWidgets.QLabel(self.tabFile)
        self.lblTotalFiles.setGeometry(QtCore.QRect(315, 126, 61, 16))
        self.lblTotalFiles.setObjectName("lblTotalFiles")
        self.lstFileList = QtWidgets.QListWidget(self.tabFile)
        self.lstFileList.setGeometry(QtCore.QRect(10, 10, 291, 131))
        self.lstFileList.setObjectName("lstFileList")
        self.btnClearList = QtWidgets.QPushButton(self.tabFile)
        self.btnClearList.setGeometry(QtCore.QRect(315, 32, 61, 17))
        self.btnClearList.setObjectName("btnClearList")
        self.btnMoveUpFile = QtWidgets.QPushButton(self.tabFile)
        self.btnMoveUpFile.setGeometry(QtCore.QRect(315, 87, 61, 17))
        self.btnMoveUpFile.setObjectName("btnMoveUpFile")
        self.btnDeleteFile = QtWidgets.QPushButton(self.tabFile)
        self.btnDeleteFile.setGeometry(QtCore.QRect(315, 108, 61, 17))
        self.btnDeleteFile.setObjectName("btnDeleteFile")
        self.tabWidget.addTab(self.tabFile, "")
        self.tabAudio = QtWidgets.QWidget()
        self.tabAudio.setObjectName("tabAudio")
        self.ckbxNoAudio = QtWidgets.QCheckBox(self.tabAudio)
        self.ckbxNoAudio.setGeometry(QtCore.QRect(10, 5, 53, 14))
        self.ckbxNoAudio.setObjectName("ckbxNoAudio")
        self.gbxAudioConfig = QtWidgets.QGroupBox(self.tabAudio)
        self.gbxAudioConfig.setEnabled(True)
        self.gbxAudioConfig.setGeometry(QtCore.QRect(10, 25, 191, 120))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.gbxAudioConfig.setFont(font)
        self.gbxAudioConfig.setObjectName("gbxAudioConfig")
        self.lblAudioCodec = QtWidgets.QLabel(self.gbxAudioConfig)
        self.lblAudioCodec.setGeometry(QtCore.QRect(20, 40, 64, 16))
        self.lblAudioCodec.setObjectName("lblAudioCodec")
        self.lblAudioType = QtWidgets.QLabel(self.gbxAudioConfig)
        self.lblAudioType.setGeometry(QtCore.QRect(20, 20, 50, 16))
        self.lblAudioType.setObjectName("lblAudioType")
        self.cbbxAudioType = QtWidgets.QComboBox(self.gbxAudioConfig)
        self.cbbxAudioType.setGeometry(QtCore.QRect(80, 20, 100, 16))
        self.cbbxAudioType.setObjectName("cbbxAudioType")
        self.cbbxAudioType.addItem("")
        self.lblAudioBitRate = QtWidgets.QLabel(self.gbxAudioConfig)
        self.lblAudioBitRate.setGeometry(QtCore.QRect(20, 60, 41, 16))
        self.lblAudioBitRate.setObjectName("lblAudioBitRate")
        self.cbbxAudioCodec = QtWidgets.QComboBox(self.gbxAudioConfig)
        self.cbbxAudioCodec.setGeometry(QtCore.QRect(80, 40, 100, 16))
        self.cbbxAudioCodec.setObjectName("cbbxAudioCodec")
        self.cbbxAudioCodec.addItem("")
        self.cbbxAudioCodec.addItem("")
        self.spbxAudioBitRate = QtWidgets.QSpinBox(self.gbxAudioConfig)
        self.spbxAudioBitRate.setEnabled(False)
        self.spbxAudioBitRate.setGeometry(QtCore.QRect(90, 94, 50, 16))
        self.spbxAudioBitRate.setObjectName("spbxAudioBitRate")
        self.lblAudioKbps = QtWidgets.QLabel(self.gbxAudioConfig)
        self.lblAudioKbps.setGeometry(QtCore.QRect(150, 96, 30, 10))
        self.lblAudioKbps.setObjectName("lblAudioKbps")
        self.rbtnBitRateAuto = QtWidgets.QRadioButton(self.gbxAudioConfig)
        self.rbtnBitRateAuto.setGeometry(QtCore.QRect(30, 77, 100, 14))
        self.rbtnBitRateAuto.setChecked(True)
        self.rbtnBitRateAuto.setObjectName("rbtnBitRateAuto")
        self.rbtnBitRateManual = QtWidgets.QRadioButton(self.gbxAudioConfig)
        self.rbtnBitRateManual.setGeometry(QtCore.QRect(30, 95, 62, 14))
        self.rbtnBitRateManual.setObjectName("rbtnBitRateManual")
        self.btnAudioRun = QtWidgets.QPushButton(self.tabAudio)
        self.btnAudioRun.setGeometry(QtCore.QRect(320, 3, 56, 17))
        self.btnAudioRun.setObjectName("btnAudioRun")
        self.tabWidget.addTab(self.tabAudio, "")
        self.tabAdvance = QtWidgets.QWidget()
        self.tabAdvance.setObjectName("tabAdvance")
        self.tbxAdvanceCmd = QtWidgets.QPlainTextEdit(self.tabAdvance)
        self.tbxAdvanceCmd.setGeometry(QtCore.QRect(8, 20, 370, 30))
        self.tbxAdvanceCmd.setObjectName("tbxAdvanceCmd")
        self.lblAdvanceCmd = QtWidgets.QLabel(self.tabAdvance)
        self.lblAdvanceCmd.setGeometry(QtCore.QRect(10, 5, 81, 14))
        self.lblAdvanceCmd.setObjectName("lblAdvanceCmd")
        self.btnAdvanceRun = QtWidgets.QPushButton(self.tabAdvance)
        self.btnAdvanceRun.setGeometry(QtCore.QRect(320, 3, 56, 14))
        self.btnAdvanceRun.setObjectName("btnAdvanceRun")
        self.txeAdvanceOutput = QtWidgets.QTextEdit(self.tabAdvance)
        self.txeAdvanceOutput.setGeometry(QtCore.QRect(8, 53, 370, 90))
        self.txeAdvanceOutput.setReadOnly(True)
        self.txeAdvanceOutput.setObjectName("txeAdvanceOutput")
        self.tabWidget.addTab(self.tabAdvance, "")
        self.tabAbout = QtWidgets.QWidget()
        self.tabAbout.setObjectName("tabAbout")
        self.tbrAbout = QtWidgets.QTextBrowser(self.tabAbout)
        self.tbrAbout.setGeometry(QtCore.QRect(10, 10, 361, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbrAbout.sizePolicy().hasHeightForWidth())
        self.tbrAbout.setSizePolicy(sizePolicy)
        self.tbrAbout.setOpenExternalLinks(True)
        self.tbrAbout.setObjectName("tbrAbout")
        self.tabWidget.addTab(self.tabAbout, "")
        winMain.setCentralWidget(self.centralwidget)

        self.retranslateUi(winMain)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(winMain)

    def retranslateUi(self, winMain):
        _translate = QtCore.QCoreApplication.translate
        winMain.setWindowTitle(_translate("winMain", "QffmpegUI"))
        self.btnFileBrowser.setText(_translate("winMain", "Add Files"))
        self.lblTotalFiles.setText(_translate("winMain", "0 files selected."))
        self.btnClearList.setText(_translate("winMain", "Clear List"))
        self.btnMoveUpFile.setText(_translate("winMain", "Move Up"))
        self.btnDeleteFile.setText(_translate("winMain", "Remove"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFile), _translate("winMain", "File"))
        self.ckbxNoAudio.setText(_translate("winMain", "No Audio"))
        self.gbxAudioConfig.setTitle(_translate("winMain", "Audio Config"))
        self.lblAudioCodec.setText(_translate("winMain", "Audio Codec:"))
        self.lblAudioType.setText(_translate("winMain", "Audio Type:"))
        self.cbbxAudioType.setItemText(0, _translate("winMain", "MP3"))
        self.lblAudioBitRate.setText(_translate("winMain", "Bit rate:"))
        self.cbbxAudioCodec.setItemText(0, _translate("winMain", "(Auto)"))
        self.cbbxAudioCodec.setItemText(1, _translate("winMain", "libmp3lame"))
        self.lblAudioKbps.setText(_translate("winMain", "Kbps"))
        self.rbtnBitRateAuto.setText(_translate("winMain", "Default / Auto Bit Rate"))
        self.rbtnBitRateManual.setText(_translate("winMain", "Manual"))
        self.btnAudioRun.setText(_translate("winMain", "Run"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAudio), _translate("winMain", "Audio"))
        self.tbxAdvanceCmd.setPlainText(_translate("winMain", "ffmpeg -version"))
        self.lblAdvanceCmd.setText(_translate("winMain", "Advance Command"))
        self.btnAdvanceRun.setText(_translate("winMain", "Run"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAdvance), _translate("winMain", "Advance"))
        self.tbrAbout.setHtml(_translate("winMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#ff5500;\">QffmpegUI</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Version beta</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Update in April 2020</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">An opensource GUI tool developed under Python to deliver FFmpeg features.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">-----</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Repo: <a href=\"https://github.com/wklchris/QffmpegUI\"><span style=\" text-decoration: underline; color:#0000ff;\">wklchris/QffmpegUI</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">License: LGPL v2.1</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAbout), _translate("winMain", "About"))
